"""initial_schema

Revision ID: d5c815e38805
Revises: 
Create Date: 2026-05-21 07:36:48.935991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c815e38805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variant_a_config', sa.Text(), nullable=False),
    sa.Column('variant_b_config', sa.Text(), nullable=False),
    sa.Column('metric_to_track', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_slug', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('target_user', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('mvp_scope', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('recommended_implementation', sa.Text(), nullable=False),
    sa.Column('score_pain', sa.Integer(), nullable=False),
    sa.Column('score_frequency', sa.Integer(), nullable=False),
    sa.Column('score_fit', sa.Integer(), nullable=False),
    sa.Column('score_simplicity', sa.Integer(), nullable=False),
    sa.Column('score_seo', sa.Integer(), nullable=False),
    sa.Column('score_monetization', sa.Integer(), nullable=False),
    sa.Column('score_risk', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_slug'), 'opportunities', ['slug'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=255), nullable=True),
    sa.Column('test_results', sa.Text(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builds')
    op.drop_table('signals')
    op.drop_index(op.f('ix_opportunities_slug'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('metrics')
    op.drop_table('experiments')
    # ### end Alembic commands ###
